### ISSUE TITLE
Question: How are multiple "overlapping" events supported? 

### ISSUE THREAD

**Issue by benmccallum** [JonPSmith/EfCore.GenericEventRunner#1]
Say I have a `Booking`, and it has a relation to a `BookingStatus`, what would happen if someone modified the FK / navigation property multiple times, say to status "In Progress" then status "Complete" before a `SaveChanges()`? Would this store the events separately and fire both of them? 

It looks like both events are certainly gathered up in the default implementation of `EntityEventsBase` [here](https://github.com/JonPSmith/EfCore.GenericEventRunner/blob/master/GenericEventRunner.DomainParts/EntityEventsBase.cs), so unless there's de-duping happening in the event firer, just wondering.

Theoretically the later one is the only one that'd ever get persisted to the database.

I guess this could be considered a bug in the code that's modifying the property multiple times.

**Comment by benmccallum** [comment]
Went digging into the handlers but it was a bit too much for me to digest at the moment!

**Comment by benmccallum** [comment]
I guess I could also implement the interface/s as needed and then de-dupe myself if ever needed.

**Comment by JonPSmith** [comment]
Hi @benmccallum,

Yes, if you have an event that happens every time you change something, then you will get a `IEntityEvent` for each change. These will be run in the order they were added - so for your example of a event will be added twice: one for the "In Progress" status and one for the status "Complete". That will cause  the appropriate event handler to be called twice. 

This isn't a bug - its how it should work (you might want to log every change of status), but as you say you must be aware this can happen. Here are some things to think about
* Does it matter if your event handler is called twice? It depends what it is doing
   - If its updating a property somewhere then it doesn't matter, as the second event will overwrite the first (your event handler is *idempotent*, i.e. calling the event handler with the same data will always produce the same result).
   - If you are creating/deleting something, then it does matter and you need to look for duplicates. There are lots of ways to do that - using a unique value (GUID?) per instance of the entity class is the normal way. 
* What status value that your event handler gets depends on what your event contains. If you send the status in the domain event, then the event handler can get each status: "In Progress" then "Complete". But if your event handler gets the status by reading the `Status` in the entity class, then the two calls to the event handler will both have the status "Complete". That's because the entity class's `Status` property only has the final status value.

Yep, these domain events are a bit more complicated and you do need to think it through a bit more. Glad you spotted this one!

**Comment by benmccallum** [comment]
That's @JonPSmith for your detailed response. You raise a good point about referring the entity itself in the handler rather than a property on the raised event.

In my case I was looking for an elegant way to inform an external system of a booking status change and so the duplication is something I just need to be aware of. We have fairly small tight mutations, so I'm not too worried, was just interested.

Another question that comes to mind quickly is how this works in terms of transactions. Does a SaveChanges inside a transaction fire the event handlers or does it only call them on commit? Apologies if this is documented somewhere, I'll have a look tomorrow when I'm back online and I'll close this up.

**Comment by JonPSmith** [comment]
Hi @benmccallum,

Your use case sounds like you need [During events, known as integration events](https://github.com/JonPSmith/EfCore.GenericEventRunner/wiki/Creating-events#2-during-events-known-as-integration-events). This makes your database update and the external system linked together - if the database update fails it won't call your external system, and if your external system fails then the database isn't updated (yes, it uses a transaction).

I plan to write more about During events - they will be in chapter 12 of my book [Entity Framework Core in Action](https://bit.ly/EfCoreBook2).

All the best with your project.

**Comment by benmccallum** [comment]
Thanks Jon, I'd seen those and indeed those are a great fit for a lot of these types of scenarios. Cheers again :)
