### ISSUE TITLE
Possible to support DbContext pooling?

### ISSUE THREAD

**Issue by benmccallum** [JonPSmith/EfCore.GenericEventRunner#3]
As it stands now, with DI into the DbContext constructor, and indeed a separate state on the context that EF Core is unaware it would need to clear, it does sound like this library wouldn't fit with pooling as per docs on the subject.

Unfortunately we are already using pooling, so it's a hard sell for us to turn that off to use this library.

I'm wondering if pooling support would be possible though if you had any ideas? The only foolproof one I have at the moment though is that the SaveChanges accepts the IEventsRunner, but that's painful for obvious reasons. Otherwise we'd be looking at the runner being resolved some other ninja way or being Singleton... Interested to hear your thoughts :)

**Comment by benmccallum** [comment]
Was thinking further about passing the `IEventsRunner` into SaveChanges, but there's also a `StatusFromLastSaveChanges` property which is essentially state on the DbContext, which puts this firmly into the "don't do pooling" category as decribed in the [ms docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/context-pooling#limitations).

**Comment by JonPSmith** [comment]
Hi @benmccallum,

OK, I think your right to not use my library, but I *think* it would work. I looked though the code and the only thing that is held is a UniqueValue which is for a use case that you won't be using (because I haven't described it in the docs 😄). The `StatusFromLastSaveChanges` isn't that important, and it would work, but it wouldn't be null if SaveChanges hasn't been called.

The two important thing are:
1.  It deletes all the Entity events - the design relies on that. 
2. It creates new event handlers each time by using the NET DI provider. That means you get fresh event handlers every time.

Maybe you can pick out some code to help you build your own version, but I must admit its pretty complex!

**Comment by benmccallum** [comment]
Thanks Jon, in the end I abandoned this for now as we need to go live this weekend but I do plan on revisiting this in future. Maybe in tandem with EF Core 5, as the events / interceptors will be interesting in relation to all this.

Appreciate your time, this is a great library and concept you've built here.

**Comment by JonPSmith** [comment]
I am reopening this so that I study support DbContext pooling in more detail.
